const ALL_QUESTIONS = [
  { id: 1, question: "He likes compact cameras.", options: { a: "Modern and expensive", b: "cheap and easy to find", c: "small and easy to carry", d: "colorful and durable" }, correct: "c" },
  { id: 2, question: "By next month, I ...in the navy for 22 years.", options: { a: "Have been", b: "will be", c: "will have", d: "will have been" }, correct: "d" },
  { id: 3, question: "They looked at the diamond with rapture.", options: { a: "Anguish", b: "agony", c: "ecstasy", d: "affiliation" }, correct: "c" },
  { id: 4, question: "By 2015, Europe train traffic will quadruple.", options: { a: "It\'ll become five times as great.", b: "It\'ll become four times less.", c: "I\'ll become four times as great.", d: "it\'ll become six as great." }, correct: "c" },
  { id: 5, question: "Tom loved to tantalize me with ice-cream and popcorn.", options: { a: "Cheer up", b: "please", c: "tease", d: "delight" }, correct: "c" },
  { id: 6, question: "Jason: Do you think the jury will believe Bob\'s story? Mike: He does ...", options: { a: "Bob is in a wheelchair.", b: "Bob has no defense", c: "Bob has never done anything wrong", d: "Bob is tired of standing." }, correct: "c" },
  { id: 7, question: "His latent talent for drawing was discovered lately.", options: { a: "Dormant", b: "patent", c: "separative", d: "dynamic" }, correct: "a" },
  { id: 8, question: "Col. Danby: Have you finished the report yet? Maj. Kelly: No. Sir, we need to put our heads together and come up with a conclusion.", options: { a: "We need to stay close to each other.", b: "We need to come to an agreement .", c: "we need to work together.", d: "we need to be careful about the conclusion." }, correct: "c" },
  { id: 9, question: "All their recent decisions undermined this financial status.", options: { a: "Reinforced", b: "wielded", c: "weakened", d: "waived" }, correct: "c" },
  { id: 10, question: "Several students are slouching in the campus. The students", options: { a: "Moving lazily", b: "playing music", c: "chatting", d: "walking fast" }, correct: "a" },
  { id: 11, question: "She likes making my hair stand on end.", options: { a: "Scaring me", b: "encouraging me", c: "making fun of me", d: "amusing me" }, correct: "a" },
  { id: 12, question: "Fatty snacks will soon lose their allure over time. What will they lose?", options: { a: "Poor quality", b: "bad odor", c: "exciting appeal", d: "shape" }, correct: "c" },
  { id: 13, question: "The house is part of local history and should be preserved.", options: { a: "Leased", b: "conserved", c: "abolished", d: "demolished" }, correct: "b" },
  { id: 14, question: "Some of the cream we have ...sour.", options: { a: "Tasty", b: "tastes", c: "tasted", d: "taste" }, correct: "b" },
  { id: 15, question: "The student can not ...the Japanese lecture.", options: { a: "Comprehend", b: "interrogate", c: "relieve", d: "represent" }, correct: "a" },
  { id: 16, question: "I haven\'t seen the Smiths for a long time. They ... abroad.", options: { a: "Can have be", b: "could have be", c: "should have been", d: "must have" }, correct: "d" },
  { id: 17, question: "We involved ourselves in the assignment with unfaltering determination.", options: { a: "Halting", b: "abiding", c: "vacillating", d: "tentative" }, correct: "b" },
  { id: 18, question: "We went ...last weekend in the lake.", options: { a: "Swimming", b: "swim", c: "to swimming", d: "swam" }, correct: "a" },
  { id: 19, question: "I don\'t think that he is to blame for breaking the computer.", options: { a: "At fault", b: "at peace", c: "at hand", d: "at risk" }, correct: "a" },
  { id: 20, question: "We have been good friends for a long time. We\'ve known ...since we were children.", options: { a: "another", b: "other", c: "one after the other", d: "one another" }, correct: "d" },
  { id: 21, question: "Phil: Whose car is that? Marina: I have no idea ...", options: { a: "whose car is it", b: "whose car is that?", c: "whose car it is?", d: "whose car it is" }, correct: "c" },
  { id: 22, question: "His eccentric behavior lost him his job. He lost his job because of his ...behavior.", options: { a: "straight", b: "peculiar", c: "harsh", d: "complacent" }, correct: "b" },
  { id: 23, question: "The fireman has trouble ...the fire.", options: { a: "extinguishing", b: "extinguish", c: "to extinguish", d: "extinguishes" }, correct: "a" },
  { id: 24, question: "The present law has failed to achieve its objectives. The aims were never ...", options: { a: "Reviewed", b: "increased", c: "reached", d: "defined" }, correct: "c" },
  { id: 25, question: "Could you give me a bag of potato chips ...this milk.", options: { a: "Come along with", b: "chip in on", c: "no matter what", d: "in exchange" }, correct: "d" },
  { id: 26, question: "Living conditions at the camp were intolerable.", options: { a: "Unconditional", b: "unattainable", c: "unbeatable", d: "unbearable" }, correct: "d" },
  { id: 27, question: "The airman just completed a course in the ...", options: { a: "Facilities", b: "dimensions", c: "evidence", d: "fundamentals" }, correct: "d" },
  { id: 28, question: "There must be some rational explanation for the bizarre action. The reason for this action must be ...", options: { a: "Influential", b: "hidden", c: "superficial", d: "logical" }, correct: "d" },
  { id: 29, question: "A NASA spokesman said that the satellite will be launched. ...the rocket.", options: { a: "Destroyed", b: "manufactured", c: "fired", d: "repaired" }, correct: "c" },
  { id: 30, question: "..., they had no chance of winning.", options: { a: "They fight as bravely.", b: "Bravely as fighting", c: "Bravely as they fought", d: "they bravely fought" }, correct: "c" },
  { id: 31, question: "It\'s essential that Peter ...on time for his lectures.", options: { a: "Were", b: "be", c: "is", d: "was" }, correct: "b" },
  { id: 32, question: "Could you check my work ...for mistakes before I hand it in?", options: { a: "Out", b: "up", c: "in", d: "over" }, correct: "d" },
  { id: 33, question: "We were ...broke after our shopping trap.", options: { a: "Quietly", b: "fair", c: "awfully", d: "awful" }, correct: "c" },
  { id: 34, question: "Someone who is always unhappy might bring you ...", options: { a: "Up", b: "down", c: "to", d: "in" }, correct: "b" },
  { id: 35, question: "Raymond did me a favor yesterday. He ...", options: { a: "Asked me to help him", b: "didn\'t need help", c: "helped me", d: "didn\'t help me" }, correct: "c" },
  { id: 36, question: "Up to twenty users can have simultaneous access to the system. Users can work ...", options: { a: "For very short time", b: "at the same time", c: "separately", d: "permenantly" }, correct: "b" },
  { id: 37, question: "Mat speaks French too rapidly ...", options: { a: "For me to understand", b: "to me for understanding", c: "for me for understanding", d: "to me to understand" }, correct: "d" },
  { id: 38, question: "It is too much of a hassle to use both toothpaste and mouthwash, isn\'t it? The process of using both is ...", options: { a: "aggravating", b: "proper", c: "complete", d: "pleasing" }, correct: "a" },
  { id: 39, question: "Meat, vegetables, dairy, napkins and noodles are examples of ...", options: { a: "recipes", b: "raw material", c: "groceries", d: "dried fruit" }, correct: "c" },
  { id: 40, question: "The doctor may be able to ...you something for that cough.", options: { a: "prevent", b: "preserve", c: "rehabilitate", d: "prescribe" }, correct: "d" },
  { id: 41, question: "The tired soldier ...while having the briefing.", options: { a: "Dropped out of", b: "dropped by", c: "dropped in", d: "dropped off" }, correct: "d" },
  { id: 42, question: "Rub this ointment into your skin. It will inhibit the infection\'s attempt to spread. The ointment will ... the spread of infection.", options: { a: "block or slow down", b: "live in a certain place", c: "somewhat enhance", d: "itch or burn" }, correct: "a" },
  { id: 43, question: "Did he ...you going to the drugstore with him?", options: { a: "Drop off", b: "insist on", c: "get through", d: "use up" }, correct: "b" },
  { id: 44, question: "Within the training class a dispute arose over whether, under the circumstances, assessment was acceptable. There was a(n) ...among class members.", options: { a: "aggravation", b: "quarrel", c: "resentment", d: "concord" }, correct: "b" },
  { id: 45, question: "Melvin ...about the meeting yesterday.", options: { a: "Was said", b: "was told", c: "is told", d: "was tell" }, correct: "b" },
  { id: 46, question: "It\'s a wonder to me how anyone can still be undecided about this election. These two candidates are certainly distinct. Every candidate is ...", options: { a: "Dishonest", b: "clearly different", c: "about the same age", d: "patriotic" }, correct: "b" },
  { id: 47, question: "Martha doesn\'t like Chinese food, and ...", options: { a: "They do too", b: "neither they do", c: "they don\'t neither", d: "neither do they" }, correct: "d" },
  { id: 48, question: "They went to Houston on a tour. They stayed there ...and came back this morning.", options: { a: "Check out", b: "final", c: "overnight", d: "rest" }, correct: "c" },
  { id: 49, question: "I bought a black pair of pants.", options: { a: "Shoes", b: "gloves", c: "trousers", d: "socks" }, correct: "c" },
  { id: 50, question: "The scores on the final test were incredible.", options: { a: "Predicted", b: "standard", c: "unbelievable", d: "ordinary" }, correct: "c" },
  { id: 51, question: "The people who applied for the secretary job were told that they would be ...of the manager\'s decision in 10 days.", options: { a: "engaged", b: "alerted", c: "settled", d: "notified" }, correct: "d" },
  { id: 52, question: "Because he refused to study for the Book Quiz, he ...a score.", options: { a: "get", b: "got", c: "getting", d: "was get" }, correct: "b" },
  { id: 53, question: "We attacked the enemy with lethal force.", options: { a: "negligible", b: "minor", c: "deadly", d: "soothing" }, correct: "c" },
  { id: 54, question: "It is absolutely essential that Joe ...80 on his next ECL.", options: { a: "to get", b: "get", c: "got", d: "gets" }, correct: "b" },
  { id: 55, question: "My son wanted to go to the beach ...the heavy rain.", options: { a: "In despite", b: "despite of", c: "in spite of", d: "in spite" }, correct: "c" },
  { id: 56, question: "I would be wary of anything he tells you.", options: { a: "Gullible", b: "accepting", c: "cautious", d: "approving" }, correct: "c" },
  { id: 57, question: "All of the soldiers seemed sluggish during the parade practice.", options: { a: "Energetic", b: "slow and lazy", c: "vivacious", d: "vigorous" }, correct: "b" },
  { id: 58, question: "The company had to go through a lot of red tape to get its plans approved. The company had to deal with the problem of ...", options: { a: "Unexpected cost increases", b: "quick preliminary meetings", c: "angry protests by workers", d: "bureaucratic procedures" }, correct: "d" },
  { id: 59, question: "I will ...about the M-16 and how to disassemble it.", options: { a: "explain you", b: "going to explain you", c: "explain to you", d: "splain you" }, correct: "c" },
  { id: 60, question: "Tom needs some ...to do this job, he can\'t work by himself.", options: { a: "confidence", b: "laziness", c: "tolerance", d: "assistance" }, correct: "d" },
  { id: 61, question: "A leader must have a lot of confidence ...his soldiers.", options: { a: "Of", b: "at", c: "in", d: "to" }, correct: "c" },
  { id: 62, question: "Learning a second language requires a great deal of determination and effect. A person must concentrate on the material. The learner must immerse himself. According to the paragraph, ...", options: { a: "It is easy to learn a second language.", b: "occasional studying results in second language learning", c: "second language learning demands hard work", d: "a person needs only to listen to learn a second language" }, correct: "c" },
  { id: 63, question: "The meeting is compulsory. Every one ...attend.", options: { a: "Must", b: "should", c: "may", d: "have got to" }, correct: "a" },
  { id: 64, question: "The atmosphere is actually part of the earth. It rotates with the earth in space and can be considered a gaseous outer cover of the earth. According to this paragraph, ...", options: { a: "The ground is part of the atmosphere", b: "The earth rotates without the atmosphere", c: "The atmosphere rotates around the earth", d: "The earth and atmosphere rotate together" }, correct: "d" },
  { id: 65, question: "Sherry drives ...", options: { a: "the most carefully", b: "the more careful", c: "the most careful", d: "more careful" }, correct: "a" },
  { id: 66, question: "They have a ...plan.", options: { a: "controversial", b: "secret", c: "contingency", d: "peace" }, correct: "c" },
  { id: 67, question: "The heavy rain caused a lot of ... in the valley.", options: { a: "reflection", b: "destruction", c: "crops", d: "location" }, correct: "b" },
  { id: 68, question: "...are clocks.", options: { a: "These", b: "This", c: "That", d: "The" }, correct: "a" },
  { id: 69, question: "...is that room?", options: { a: "How length", b: "What long", c: "How long", d: "What length" }, correct: "c" },
  { id: 70, question: "\"Tina needs some more cigarettes. Does Paul have any?\" \"...,\"", options: { a: "No, he has none", b: "No, he has any", c: "No, he doesn\'t have some", d: "yes, he has any" }, correct: "a" },
  { id: 71, question: "Alan wants to be an airplane mechanic, ...he\'s going to a technical s...", options: { a: "or", b: "because", c: "if", d: "so" }, correct: "d" },
  { id: 72, question: "We have to determine ...ammunition the", options: { a: "how many – have", b: "how much- is have", c: "amount- having", d: "how much- has" }, correct: "d" },
  { id: 73, question: "Some divers may use hand arm ...", options: { a: "lanes", b: "limits", c: "signals", d: "cautions" }, correct: "c" },
  { id: 74, question: "Hay! It\'s too loud. Could you ...the volume, please, by turning it down?", options: { a: "install", b: "adjust", c: "shut down", d: "assemble" }, correct: "b" },
  { id: 75, question: "The prices at this supermarket are not high. They are ...", options: { a: "busy", b: "boring", c: "sharp", d: "reasonable" }, correct: "d" },
  { id: 76, question: "There has been a ...in that store\'s prices.", options: { a: "Reduction", b: "reduce", c: "reduces", d: "to reduce" }, correct: "a" },
  { id: 77, question: "When you want to ask a question, ...your hand.", options: { a: "replace", b: "collect", c: "remove", d: "raise" }, correct: "d" },
  { id: 78, question: "The medicine tastes ...", options: { a: "bad", b: "badly", c: "well", d: "worse" }, correct: "a" },
  { id: 79, question: "I think that our cars are ...", options: { a: "Similar", b: "like", c: "similar to", d: "the same as" }, correct: "a" },
  { id: 80, question: "The parachutist ...his legs when he landed roughly and some rocks.", options: { a: "hurting", b: "hurted", c: "hurts", d: "hurt" }, correct: "d" },
  { id: 81, question: "Go three ..., then turn left.", options: { a: "Moments", b: "gardens", c: "parks", d: "blocks" }, correct: "d" },
  { id: 82, question: "One Echo Company private ...from the BX.", options: { a: "Shoplifted", b: "shoplift", c: "was shoplifted", d: "was shoplift" }, correct: "a" },
  { id: 83, question: "A train is faster than a car but an airplane is ...", options: { a: "the fastest", b: "the faster", c: "the fast", d: "faster than" }, correct: "a" },
  { id: 84, question: "I anticipate ...back home in a few week.", options: { a: "To be go", b: "going", c: "to go", d: "go" }, correct: "b" },
  { id: 85, question: "The general ordered that Sgt Smith ...in his office at 0700.", options: { a: "Be", b: "was", c: "being", d: "is" }, correct: "a" },
  { id: 86, question: "The young woman purposely signed the wrong name on the document. She ...the document.", options: { a: "Falsification", b: "falsify", c: "false", d: "falsified" }, correct: "d" },
  { id: 87, question: "Mary can write equally well with both her left and right hands. She is ...", options: { a: "Amphibious", b: "ambiguous", c: "ambidextrous", d: "ambulatory" }, correct: "c" },
  { id: 88, question: "Steve has many outstanding attributes, not the least of which is his impeccable appearance.", options: { a: "Steve would be outstanding if he weren\'t sloppy.", b: "Steve looks bad most of the time.", c: "Steve is usually neat and clean.", d: "Steve has no outstanding attributes." }, correct: "c" },
  { id: 89, question: "Sgt. Huber: I talked to the commander yesterday and he approved the change in your orders that you asked for. Pvt. Davis: Hey, thanks for sticking your neck out for me.", options: { a: "Thanks for deciding for me.", b: "Thanks for taking my place", c: "thanks for taking the risk to help me.", d: "thanks for letting me use your office." }, correct: "c" },
  { id: 90, question: "I want your report about the helicopter repairs to be as succinct as possible.", options: { a: "clear and brief", b: "vague and pointless", c: "erroneous and flawed", d: "long and" }, correct: "a" },
  { id: 91, question: "Sally: Would you like to go to lunch with us today? Katy: You ...I need to save my money. Sally: That\'s okay. Larry is going to foot the bill. ...", options: { a: "Leave the restaurant without paying", b: "Make everyone pay him later", c: "lend everyone some money", d: "pay for everyone" }, correct: "d" },
  { id: 92, question: "Cuba has the best ...in the world.", options: { a: "cigars factory", b: "cigar manufactory", c: "cigars factories", d: "cigar" }, correct: "a" },
  { id: 93, question: "It is I who ...your next teacher.", options: { a: "Are", b: "were", c: "am", d: "is" }, correct: "c" },
  { id: 94, question: "My son is very awkward when he tries to ride his new bicycle.", options: { a: "Clumsy", b: "proficient", c: "irritated", d: "graceful" }, correct: "a" },
  { id: 95, question: "I had the dog ... the bone.", options: { a: "Fetch", b: "fetching", c: "fetches", d: "fetched" }, correct: "a" },
  { id: 96, question: "Americans always ...on weekends.", options: { a: "Went window shopping", b: "are window shop", d: "go window shopping" }, correct: "d" },
  { id: 97, question: "John is ...success.", options: { a: "thirsty", b: "thirsty for", c: "thirsty of", d: "thirsty in" }, correct: "b" },
  { id: 98, question: "After numerous times trying to apply for a visa, his immigration fizzled.", options: { a: "Impressed", b: "succeeded", c: "failed", d: "worked" }, correct: "c" },
  { id: 99, question: "In those ancient times his ideas about religion were considered ...", options: { a: "Heresy", b: "heritage", c: "hereafter", d: "hearsay" }, correct: "a" },
  { id: 100, question: "Darkness began to fall, the sounds of insects began to rise, , to flush out any intruders, Sgt Don lobbed several gardens around the platoon position.", options: { a: "Threw", b: "saved", c: "hid", d: "stole" }, correct: "a" },
  { id: 101, question: "The story about his alleged affairs smeared his good.", options: { a: "Quaffed", b: "tainted", c: "dawdled", d: "rallied" }, correct: "b" },
  { id: 102, question: "My refusal to this offer is unequivocal.", options: { a: "Hazy", b: "ambivalent", c: "clear", d: "obscure" }, correct: "c" },
  { id: 103, question: "John left his position with the company because he left that advancement was based on nepotism rather than ability.", options: { a: "Performance", b: "caliber", c: "creativity", d: "favoritism to a relative" }, correct: "d" },
  { id: 104, question: "Don\'t you have the nerve to tell the truth?", options: { a: "Courage", b: "cowardice", c: "shyness", d: "timidity" }, correct: "a" },
  { id: 105, question: "All their recent decisions undermined this financial status.", options: { a: "Waived", b: "reinforced", c: "weakened", d: "wielded" }, correct: "c" },
  { id: 106, question: "The young man found himself unable to resist the magic effect of the perfume as it ...in the air.", options: { a: "Crawled", b: "lingered", c: "wandered", d: "misled" }, correct: "b" },
  { id: 107, question: "He hurt his shin, so it is hard for him to ...", options: { a: "Eat", b: "yawn", c: "speak", d: "kneel" }, correct: "d" },
  { id: 108, question: "Perplexed about the assignments, John could ..with such an arduous task. He was ...", options: { a: "Certain", b: "confident", c: "amused", d: "baffled" }, correct: "d" },
  { id: 109, question: "How\'s your uncle feeling?", options: { a: "He\'s better, thanks.", b: "He isn\'t here", c: "Certainly, he is", d: "No, he isn\'t" }, correct: "a" },
  { id: 110, question: "She was up a creek without a paddle.", options: { a: "Angry", b: "in time", c: "in difficulty", d: "in prosperity" }, correct: "c" },
  { id: 111, question: "She forced her way into the house and ransacked all my drawers.", options: { a: "Presided", b: "raided", c: "struck", d: "searched" }, correct: "d" },
  { id: 112, question: "They imposed a very high tariff on cosmetics.", options: { a: "Tax", b: "division", c: "coalition", d: "decoration" }, correct: "a" },
  { id: 113, question: "The stuffy room is smothering.", options: { a: "Hairsplitting", b: "skidding", c: "suffocating", d: "ventilating" }, correct: "c" },
  { id: 114, question: "They looked at the diamond with rapture.", options: { a: "Anguish", b: "affliction", c: "ecstasy", d: "agony" }, correct: "c" },
  { id: 115, question: "Only three people survived the accident. Only three people ...", options: { a: "Were reversed", b: "were sustained", c: "were saved", d: "were killed" }, correct: "c" },
  { id: 116, question: "It\'s evident that she was involved in the murder.", options: { a: "Disturbing", b: "clear", c: "doubtful", d: "ambiguous" }, correct: "b" },
  { id: 117, question: "Smoking is a real threat to general health.", options: { a: "Pain", b: "warning", c: "defect", d: "danger" }, correct: "d" },
  { id: 118, question: "What happened to General Robert?", options: { a: "Became of", b: "felt to", c: "became", d: "created" }, correct: "a" },
  { id: 119, question: "They have some concerns about their scores.", options: { a: "Doubts", b: "graduation", c: "hopes", d: "worries" }, correct: "d" },
  { id: 120, question: "I need to convince them of our opinion about the job.", options: { a: "Persuade", b: "advise", c: "appoint", d: "agree" }, correct: "a" },
  { id: 121, question: "Drivers should obey traffic laws.", options: { a: "Rules", b: "policemen", c: "streets", d: "signals" }, correct: "a" },
  { id: 122, question: "Andy has a fever and won\'t come to work today.", options: { a: "Normal temperature", b: "high temperature", c: "regular temperature", d: "low temperature" }, correct: "b" },
  { id: 123, question: "...I you, I wouldn\'t do that.", options: { a: "Was", b: "Would be", c: "Am", d: "Were" }, correct: "d" },
  { id: 124, question: "I found Anna\'s flat ...losing her address.", options: { a: "In spite of", b: "although", c: "though", d: "if" }, correct: "a" },
  { id: 125, question: "...is one of my favorite instruments, although it is a difficult instrument to play well.", options: { a: "The violin", b: "some violin", c: "any violin", d: "A violin" }, correct: "a" },
  { id: 126, question: "Have you still got last ...newspaper?", options: { a: "Saturdays\'", b: "Saturday", c: "Saturdays", d: "Saturday\'s" }, correct: "b" },
  { id: 127, question: "The ...house is beautiful.", options: { a: "Smith", b: "Smiths\'s", c: "Smith\'s", d: "Smiths\'" }, correct: "c" },
  { id: 128, question: "Do you mind ...it with you?", options: { a: "To take", b: "taking", c: "take", d: "takes" }, correct: "b" },
  { id: 129, question: "What ...if you had seen an accident on your way here?", options: { a: "would have you done", b: "would you have done", c: "would you had done", d: "would you do" }, correct: "b" },
  { id: 130, question: "I found the old man quite changed. I ...him for years.", options: { a: "Hadn\'t seen", b: "haven\'t seen", c: "haven\'t see", d: "hasn\'t seen" }, correct: "b" },
  { id: 131, question: "She left home two hours ago, so she ...have arrived by now.", options: { a: "Can", b: "must", c: "could", d: "should" }, correct: "d" },
  { id: 132, question: "I didn\'t like ...of choices.", options: { a: "Neither", b: "so", c: "both", d: "either" }, correct: "c" },
  { id: 133, question: "A: Have you finished work? B: Yes. A: Ok, ...you in fifteen minutes.", options: { a: "I meet", b: "meets", c: "I\'m going to meet", d: "I\'ll meet" }, correct: "d" },
  { id: 134, question: "We didn\'t spend ...money.", options: { a: "Many", b: "many of", c: "much", d: "few" }, correct: "c" },
  { id: 135, question: "...any coffee in the cup?", options: { a: "There is", b: "Are there", c: "There are", d: "Is there" }, correct: "d" },
  { id: 136, question: "My family will travel ...October.", options: { a: "In", b: "on", c: "an", d: "at" }, correct: "a" },
  { id: 137, question: "I ...three letters yesterday.", options: { a: "Writes", b: "writing", c: "written", d: "wrote" }, correct: "d" },
  { id: 138, question: "Many people can\'t find permanent jobs nowadays, so they try to look for ...jobs.", options: { a: "Mobile", b: "diagonal", c: "relevant", d: "temporary" }, correct: "d" },
  { id: 139, question: "There were many ..., who needed immediate assistance.", options: { a: "Victims", b: "shocks", c: "accidents", d: "hurt" }, correct: "a" },
  { id: 140, question: "The students like Mr. William because he is very ...", options: { a: "General", b: "friendly", c: "properly", d: "fairly" }, correct: "b" },
  { id: 141, question: "She was ...of killing her husband.", options: { a: "Refused", b: "forced", c: "arrested", d: "accused" }, correct: "d" },
  { id: 142, question: "The chemicals in paint are ...to health.", options: { a: "Personal", b: "hazardous", c: "unlikely", d: "main" }, correct: "b" },
  { id: 143, question: "The ...predicts rain tomorrow on TV.", options: { a: "Scientist", b: "leader", c: "weatherman", d: "employer" }, correct: "c" },
  { id: 144, question: "The visibility is very bad here; I can\'t ...anything.", options: { a: "Warn", b: "hear", c: "see", d: "reach" }, correct: "c" },
  { id: 145, question: "The ...is a part of the car.", options: { a: "Tool", b: "Carburetor", c: "Thermostat", d: "Barometer" }, correct: "b" },
  { id: 146, question: "I can\'t concentrate on my homework; would you ...the TV?", options: { a: "Watch", b: "fix", c: "switch off", d: "switch on" }, correct: "c" },
  { id: 147, question: "She was ... 3 years ago.", options: { a: "Supposed", b: "designed", c: "worked", d: "employed" }, correct: "d" },
  { id: 148, question: "This way isn\'t safe. It\'s ...", options: { a: "Full", b: "fast", c: "dangerous", d: "bored" }, correct: "c" },
  { id: 149, question: "The coffee ...really nice.", options: { a: "Smells", b: "boils", c: "drinks", d: "cooks" }, correct: "a" },
  { id: 150, question: "They want to ...some new workers.", options: { a: "Cover", b: "hire", c: "own", d: "lie" }, correct: "b" },
  { id: 151, question: "We use the ...to stop the car.", options: { a: "Bike", b: "break", c: "brakes", d: "machine" }, correct: "c" },
  { id: 152, question: "How many ...are in this world?", options: { a: "Lessons", b: "letters", c: "names", d: "languages" }, correct: "d" },
  { id: 153, question: "They are listening to the ...", options: { a: "Radio", b: "time", c: "TV", d: "map" }, correct: "a" },
  { id: 154, question: "What is the ...to the question?", options: { a: "Homework", b: "answer", c: "word", d: "sentence" }, correct: "b" },
  { id: 155, question: "The students sit on the ...", options: { a: "School", b: "class", c: "chairs", d: "blackboard" }, correct: "c" },
  { id: 156, question: "The test was not easy. The test was ...", options: { a: "Difficult", b: "easy", c: "short", d: "not difficult" }, correct: "a" },
  { id: 157, question: "He puts the book ...the table.", options: { a: "On", b: "in", c: "from", d: "of" }, correct: "a" },
  { id: 158, question: "I ...English well.", options: { a: "Listen", b: "say", c: "speak", d: "ask" }, correct: "c" },
  { id: 159, question: "He asked about ...", options: { a: "What time did the plane take off", b: "What time the plane would take off", c: "What time the plane will take off", d: "What time will the plane take off" }, correct: "b" },
  { id: 160, question: "He said that he ...TV for two hours.", options: { a: "Was watching", b: "had been watching", c: "had being watched", d: "was being watched" }, correct: "b" },
  { id: 161, question: "They talk about the weather\'s ...", options: { a: "Severeness", b: "severing", c: "severition", d: "severity" }, correct: "d" },
  { id: 162, question: "The terrible weather affected the crops; ...", options: { a: "So", b: "because", c: "consequently", d: "although" }, correct: "c" },
  { id: 163, question: "Her behavior really began to make me angry. It ...", options: { a: "Cheered me up", b: "irritated me", c: "messed me up", d: "amazed me" }, correct: "b" },
  { id: 164, question: "The meeting will resume at 0945.", options: { a: "Begin again", b: "wind up", c: "summarize", d: "conclude" }, correct: "a" },
  { id: 165, question: "The skirmish had hardly begun when we exhausted our supply of ammo.", options: { a: "Ran away from", b: "ran through", c: "ran out of", d: "ran across to" }, correct: "c" },
  { id: 166, question: "If you ...3 by 7, you will get 21.", options: { a: "Divide", b: "subtract", c: "add", d: "multiply" }, correct: "d" },
  { id: 167, question: "I would study Friday nights in the learning Center ...", options: { a: "Were I you", b: "if I am do", c: "be I you", d: "was I you" }, correct: "a" },
  { id: 168, question: "The outfit Lt Smith\'s wife wore to the General\'s reception was unsuitable.", options: { a: "Inappropriate", b: "gorgeous", c: "tasteful", d: "perfect" }, correct: "a" },
  { id: 169, question: "Col Danby: have you finished the report yet? Maj. Kelly: No. Some time this afternoon we need to put our heads together and come up with a conclusion.", options: { a: "We need to be careful about the conclusion.", b: "We need to come to an agreement .", c: "We need to work together .", d: "We need to stay close to each other." }, correct: "c" },
  { id: 170, question: "During his briefing, he gave us a smattering of details.", options: { a: "An abundance", b: "a huge number", c: "scores", d: "not very many" }, correct: "d" },
  { id: 171, question: "Bob: What did you do at the dentist\'s? Lena: I got ...", options: { a: "the children\'s teeth cleaning", b: "the children\'s teeth clean", c: "the children\'s teeth to clean", d: "the children\'s teeth cleaned" }, correct: "d" },
  { id: 172, question: "she really regrets ...with her family during the Christmas holidays.", options: { a: "To not being", b: "not be", c: "not to be", d: "not being" }, correct: "d" },
  { id: 173, question: "The commander ...that I was the best of my class.", options: { a: "Tell me", c: "told me", d: "say to me" }, correct: "c" },
  { id: 174, question: "That movie was based on ...story.", options: { a: "A true", b: "a truth", c: "truth", d: "true" }, correct: "a" },
  { id: 175, question: "Our position ...by the enemy.", options: { a: "Were overran", b: "were overrun", c: "was overrun", d: "was overran" }, correct: "c" },
  { id: 176, question: "Our positions ...by the enemy.", options: { a: "Were overran", b: "were overrun", c: "was overrun", d: "was overran" }, correct: "b" },
  { id: 177, question: "The final thing to do is ...your troops.", options: { a: "Conciliate", b: "consequiate", c: "reconciliate", d: "reconsolidate" }, correct: "c" },
  { id: 178, question: "An offensive odor would be ...", options: { a: "a bad stink", b: "a nice aroma", c: "a wonderful fragrance", d: "a pleasant smell" }, correct: "a" },
  { id: 179, question: "He doesn\'t have to do PT because he is ...profile.", options: { a: "On", b: "of", c: "in", d: "at" }, correct: "c" },
  { id: 180, question: "I ...too sick to go to the game last night.", options: { a: "fell", b: "fall", c: "fell", d: "felt" }, correct: "d" },
  { id: 181, question: "The ...is in the front of the theatre. It\'s where the actors perform the play.", options: { a: "drama", b: "stage", c: "seat", d: "walk" }, correct: "b" },
  { id: 182, question: "I will now tell you ...", options: { a: "the procedure is what", b: "the procedure what is", c: "what the procedure is", d: "what is the procedure" }, correct: "c" },
  { id: 183, question: "If you want to get a job here in this bank, you need to go to the ...", options: { a: "promotion", b: "career", c: "opportunity", d: "personnel" }, correct: "d" },
  { id: 184, question: "If today is Tuesday, then tomorrow ...Wednesday.", options: { a: "am", b: "were", c: "was", d: "is" }, correct: "d" },
  { id: 185, question: "Pamela ...this book for a month.", options: { a: "Had has", b: "is", c: "have had", d: "has had" }, correct: "d" },
  { id: 186, question: "The prices at this supermarket are not high. They are ...", options: { a: "Sharp", b: "busy", c: "reasonable", d: "boring" }, correct: "c" },
  { id: 187, question: "I have a (n) ...with Dr. Dean this Tuesday.", options: { a: "Appointment", b: "emergency", c: "medicine", d: "symptom" }, correct: "a" },
  { id: 188, question: "Pat was a secretary before she ...Ron.", options: { a: "got married", b: "worked", c: "gets married", d: "married" }, correct: "d" },
  { id: 189, question: "I have ...problems right now.", options: { a: "Some of", b: "too many", c: "a lot", d: "too much" }, correct: "b" },
  { id: 190, question: "Ask Mr. Reply ...this letter.", options: { a: "To sign", b: "signing", c: "sign", d: "signed" }, correct: "a" },
  { id: 191, question: "A small coin worth ten cents is called ...", options: { a: "A penny", b: "a dime", c: "a quarter", d: "a nickel" }, correct: "b" },
  { id: 192, question: "I was born ...Puerto Rico.", options: { a: "of", b: "in", c: "on", d: "at" }, correct: "b" },
  { id: 193, question: "This is the ...worksheet you will ever have.", options: { a: "Most easiest", b: "easier", c: "easy", d: "easiest" }, correct: "d" },
  { id: 194, question: "The meat from a cow is called ...", options: { a: "Pork", b: "chicken", c: "fish", d: "beef" }, correct: "d" },
  { id: 195, question: "Next week will be his final week here at DLI.", options: { a: "last", b: "beginning", c: "initial", d: "first" }, correct: "a" },
  { id: 196, question: "Mark\'s airplane departed at 3:00 p.m. It will arrive ...at 10:00 p.m.", options: { a: "Round-trip", b: "off", c: "tonight", d: "together" }, correct: "c" },
  { id: 197, question: "You really should speak more English during break.", options: { a: "must", b: "have to", c: "ought to", d: "can" }, correct: "c" },
  { id: 198, question: "I ...last night. I was bored.", options: { a: "Didn\'t do nothing", b: "done nothing", c: "didn\'t do something", d: "didn\'t do anything" }, correct: "d" },
  { id: 199, question: "She never ...English.", options: { a: "speaking", b: "to speak", c: "speak", d: "speaks" }, correct: "d" },
  { id: 200, question: "Is your answer correct? ...", options: { a: "Yes, it\'s a wrong answer.", b: "Yes, it\'s the right answer", c: "No, my answer is correct", d: "Yes, you are welcome" }, correct: "b" },
  { id: 201, question: "Mary ...two brothers.", options: { a: "have", b: "are", c: "is", d: "has" }, correct: "d" },
  { id: 202, question: "English ...not easy for me.", options: { a: "Were", b: "am", c: "are", d: "is" }, correct: "d" },
  { id: 203, question: "Can you tell me ...?", options: { a: "how to wrapping this package", b: "how to wrap this package", c: "how did I wrap this package", d: "how do I wrap this package" }, correct: "d" },
  { id: 204, question: "A: Lt. Smith drew a helix on the board as part of his presentation. B: You mean he drew a ...", options: { a: "triangle", b: "square", c: "spiral", d: "circle" }, correct: "c" },
  { id: 205, question: "My sister ...to her company everyday.", options: { a: "Is walk", b: "walking", c: "walk", d: "walks" }, correct: "d" },
  { id: 206, question: "I want to stay ...France for a week or two.", options: { a: "In", b: "of", c: "on", d: "at" }, correct: "a" },
  { id: 207, question: "A: You ought to study hard, our test is tomorrow. B: Yes, we ...", options: { a: "Have to", b: "will", c: "must", d: "should" }, correct: "d" },
  { id: 208, question: "I haven\'t visited the Egyptian museum_______.", options: { a: "Never", b: "yet", c: "none", d: "still" }, correct: "b" },
  { id: 209, question: "This test is ...", options: { a: "Bored", b: "boring", c: "bores", d: "bore" }, correct: "b" },
  { id: 210, question: "The price of cars, boats, furs, and other luxury items ...rising.", options: { a: "have been", b: "are being", c: "are", d: "is" }, correct: "d" },
  { id: 211, question: "I would be careful with my answer if I ...you.", options: { a: "am", b: "will be", c: "were", d: "had been" }, correct: "c" },
  { id: 212, question: "During the last storm many houses ...", options: { a: "Have been destroying", b: "were destroyed", c: "destroying", d: "destroyed" }, correct: "b" },
  { id: 213, question: "Sheep ...grass to stay alive.", options: { a: "Need", b: "are need", c: "needing", d: "needs" }, correct: "a" },
  { id: 214, question: "Let me tell you that I ...two years for this company before I decided to resign.", options: { a: "Am work", b: "had been working", c: "was worked", d: "have been working" }, correct: "b" },
  { id: 215, question: "Where are the stamps? I clearly remember ...them in my shirt pocket.", options: { a: "To put", b: "putting", c: "put", d: "being put" }, correct: "b" },
  { id: 216, question: "The whole idea ...since he traveled abroad.", options: { a: "was neglecting", b: "neglecting", c: "has been neglected", d: "neglected" }, correct: "c" },
  { id: 217, question: "He did not wear a helmet when he rode his motorcycle, thereby ...severe injury in case of an accident.", options: { a: "risk", b: "risking", c: "risked", d: "risks" }, correct: "b" },
  { id: 218, question: "Some of the pie ...before we cut it.", options: { a: "was eaten", b: "were eaten", c: "got eat", d: "got ate" }, correct: "a" },
  { id: 219, question: "Of all the jobs Joe could have chosen, he now regrets ...the police force.", options: { a: "having joined", b: "hadn\'t joined", c: "didn\'t join", d: "were joined" }, correct: "a" },
  { id: 220, question: "..., we could not have our picnic in the park.", options: { a: "Since it was raining", b: "Because it raining", c: "Because of raining", d: "Since it was much raining" }, correct: "c" },
  { id: 221, question: "My favorite season of the year is autumn.", options: { a: "fall", b: "winter", c: "spring", d: "summer" }, correct: "a" },
  { id: 222, question: "All the competitors were required to run 10 km. in 40 min.", options: { a: "Having to", b: "had to", c: "has to", d: "have to" }, correct: "b" },
  { id: 223, question: "The exhibition ...by the minister of art tomorrow.", options: { a: "Will be opened", b: "opens", c: "will open", d: "will be opening" }, correct: "a" },
  { id: 224, question: "Don\'t carry all those ...together, they are very heavy.", options: { a: "Box\'s", b: "boxes", c: "boxs", d: "box" }, correct: "b" },
  { id: 225, question: "After you buy what you need, it is important to keep your ...", options: { a: "Measure", b: "bargain", c: "percent", d: "receipt" }, correct: "d" },
  { id: 226, question: "A: When my sister went to buy her new shoes, they were on sale. B: You mean there was a ...", options: { a: "discount", b: "disregard", c: "disorder", d: "bargain" }, correct: "a" },
  { id: 227, question: "Your TV is too ...", options: { a: "loud", b: "loudly", c: "louder", d: "louder" }, correct: "a" },
  { id: 228, question: "She speaks very ...", options: { a: "More quick", b: "quickly", c: "quicker", d: "more quickly" }, correct: "b" },
  { id: 229, question: "Check your work ...", options: { a: "more careful", b: "more carefulness", c: "careful", d: "carefully" }, correct: "d" },
  { id: 230, question: "You should report to the army ...ASAP.", options: { a: "headquarters", b: "auditorium", c: "piers", d: "council" }, correct: "a" },
  { id: 231, question: "Americans regard the half-dollar as a ...", options: { a: "treasure", b: "bad omen", c: "taboo", d: "good luck" }, correct: "d" },
  { id: 232, question: "A: I really need to speak to you now.\" B: \"Oh, all right if you ...\"", options: { a: "Complicate", b: "resist", c: "finalize", d: "insist" }, correct: "d" },
  { id: 233, question: "Several soldiers were wounded during the battle. They were ...", options: { a: "Sad", b: "caught", c: "happy", d: "hurt" }, correct: "d" },
  { id: 234, question: "Joe is too skinny. He is ...", options: { a: "Overweight", b: "chubby", c: "loud", d: "underweight" }, correct: "d" },
  { id: 235, question: "Exercising ?!!!! are you nuts?! I\'m dog tired right now.", options: { a: "Relaxed", b: "wealthy", c: "exhausted", d: "happy" }, correct: "c" },
  { id: 236, question: "Speaking of our budget, we need more funds.", options: { a: "Data", b: "appropriations", c: "supplies", d: "food" }, correct: "b" },
  { id: 237, question: "If the score is tied at nil, which of these reflects the score?", options: { a: "6-3", b: "10-1", c: "1-0", d: "0-0" }, correct: "d" },
  { id: 238, question: "The accident resulted in a slight injury to the little girl.", options: { a: "It\'s very serious", b: "It\'s not too serious", c: "She\'s in critical condition", d: "She will probably die" }, correct: "b" },
  { id: 239, question: "My Boss said, \"You have a half-dozen things to do before you go home tonight\".", options: { a: "six", b: "four", c: "twelve", d: "twenty-four" }, correct: "a" },
  { id: 240, question: "Many African countries suffer from famines.", options: { a: "conventions", b: "starvations", c: "liberations", d: "safeguards" }, correct: "b" },
  { id: 241, question: "the two countries decide to integrate their economies.", options: { a: "promote their economies", b: "join their economies", c: "promote their economies", d: "separate their economies" }, correct: "b" },
  { id: 242, question: "She compiled many facts about the crime.", options: { a: "gathered", b: "compared", c: "protected", d: "provided" }, correct: "a" },
  { id: 243, question: "Tom gets himself engaged in the action.", options: { a: "liberated", b: "excluded", c: "involved", d: "accorded" }, correct: "c" },
  { id: 244, question: "I have got a splinter in my finger.", options: { a: "ring", b: "golden bracelet", c: "small piece of wood", d: "cut" }, correct: "c" },
  { id: 245, question: "She is 90 years old but her comments are the most lucid I have ever heard.", options: { a: "Best-natured", b: "intelligible", c: "talkative", d: "active" }, correct: "b" },
  { id: 246, question: "At the ceremony as the announcer mentioned something about a fallen comrade we suddenly heard the bugle call. What did they hear?", options: { a: "taps", b: "maps", c: "flaps", d: "laps" }, correct: "a" },
  { id: 247, question: "After their period of intense exercise, all of the soldiers seemed sluggish during the parade practice.", options: { a: "vigorous", b: "energetic", c: "vivacious", d: "slow and lazy" }, correct: "d" },
  { id: 248, question: "Fred\'s beliefs about a supreme being reveal that he is less of an ...than he thinks he is.", options: { a: "An atheist", b: "a chaperon", c: "a steward", d: "a ruffian" }, correct: "a" },
  { id: 249, question: "I ... my jacket on a nail.", options: { a: "stained", b: "scuttled", c: "ripped", d: "soiled" }, correct: "c" },
  { id: 250, question: "The match will begin ...1540.", options: { a: "to", b: "at", c: "of", d: "on" }, correct: "b" },
  { id: 251, question: "A: Is this car very expensive? B: No, it is ...", options: { a: "cheapest", b: "cheap", c: "cheaper", d: "cheapless" }, correct: "b" },
  { id: 252, question: "...car is white.", options: { a: "Mine", b: "I", c: "My", d: "Me" }, correct: "c" },
  { id: 253, question: "Adam ate a couple of bananas. How many bananas did he eat?", options: { a: "two", b: "one", c: "dozen", d: "six" }, correct: "a" },
  { id: 254, question: "Yesterday, I ...eat well .", options: { a: "Does", b: "didn\'t", c: "don\'t", d: "doesn\'t" }, correct: "b" },
  { id: 255, question: "A: Did you buy a new house? B: Yes: we ...one last week.", options: { a: "Buy", b: "bought", c: "buying", d: "buys" }, correct: "b" },
  { id: 256, question: "The workers ...by the hour.", options: { a: "Paying", b: "will be pay", c: "pay", d: "are paid" }, correct: "d" },
  { id: 257, question: "This test is ...", options: { a: "Bores", b: "bore", c: "bored", d: "boring" }, correct: "d" },
  { id: 258, question: "The teacher gives ...", options: { a: "homework much", b: "too much homework", c: "too much homeworks", d: "too many homeworks" }, correct: "b" },
  { id: 259, question: "Joe has a new pair of shoes, ...?", options: { a: "Can", b: "doesn\'t he", c: "haven\'t he", d: "do he" }, correct: "b" },
  { id: 260, question: "Smoking ...in here.", options: { a: "Doesn\'t allowed", b: "not allowing", c: "isn\'t allowed", d: "don\'t allowed" }, correct: "c" },
  { id: 261, question: "...this subject at college?", options: { a: "Do you taught", b: "Have you teach", c: "Are you teaching", d: "Are you taught" }, correct: "c" },
  { id: 262, question: "You ...in prison if you are not guilty.", options: { a: "Will not put", b: "can\'t be put", c: "don\'t put", d: "can\'t put" }, correct: "b" },
  { id: 263, question: "Joe ...his ID card when he went to take the ECL.", options: { a: "No had", b: "didn\'t have", c: "had not", d: "doesn\'t have" }, correct: "b" },
  { id: 264, question: "He acts as if he ...a beautiful woman before.", options: { a: "never seen", b: "was never seen", c: "did never see", d: "had never seen" }, correct: "d" },
  { id: 265, question: "The whole idea ...since he traveled abroad.", options: { a: "Neglected", b: "was neglecting", c: "has been neglected", d: "neglecting" }, correct: "c" },
  { id: 266, question: "The police ...here twice looking for you.", options: { a: "Have been", b: "has been", c: "are", d: "was" }, correct: "a" },
  { id: 267, question: "Of your two daughters, which one is ...?", options: { a: "the oldest", b: "the old", c: "oldest", d: "the older" }, correct: "a" },
  { id: 268, question: "Do you live ...base?", options: { a: "On", b: "in", c: "of", d: "at" }, correct: "a" },
  { id: 269, question: "A: The cake is delicious. B: Yes, it\'s very ...", options: { a: "salty", b: "tasty", c: "awful", d: "terrible" }, correct: "b" },
  { id: 270, question: "The damaged ship ... to the harbor.", options: { a: "has been drawn", b: "been drawn", c: "drawn", d: "draw" }, correct: "a" },
  { id: 271, question: "She played the piano ...", options: { a: "more beauty", b: "beautiful", c: "more beautiful", d: "beautifully" }, correct: "d" },
  { id: 272, question: "An adjective that could refer to something that produces good results is ...", options: { a: "Defective", b: "careful", c: "informative", d: "fruitful" }, correct: "d" },
  { id: 273, question: "Can you ...me on what\'s been happening, please sir?", options: { a: "Preserve", b: "keep", c: "maintain", d: "update" }, correct: "d" },
  { id: 274, question: "Speaking of our budget, we need more funds.", options: { a: "appropriations", b: "supplies", c: "food", d: "data" }, correct: "a" },
  { id: 275, question: "What do we call the reddish-brown stuff that forms on metal?", options: { a: "sand", b: "rash", c: "rust", d: "skin" }, correct: "c" },
  { id: 276, question: "They respect their grandparents. They ...", options: { a: "look over them", b: "look up to them", c: "look in on them", d: "look down on" }, correct: "b" },
  { id: 277, question: "Speaking of mistakes, you have made quite a few in your speech.", options: { a: "He came through", b: "He messed up", c: "he pulled it off", d: "He hit the nail on the" }, correct: "b" },
  { id: 278, question: "You will be grounded if this room isn\'t cleaned up by noon. The room isn\'t ...", options: { a: "orderly", b: "messy", c: "soiled", d: "unorganized" }, correct: "a" },
  { id: 279, question: "Mark is a very proficient worker.", options: { a: "untrained", b: "skilled", c: "incompetent", d: "bad" }, correct: "b" },
  { id: 280, question: "The book was controversial.", options: { a: "recent", b: "simple", c: "advisory", d: "debatable" }, correct: "d" },
  { id: 281, question: "Darkness began to fall, the sounds of nocturnal insects began to rise, mysterious unidentifiable sounds began to emerge, so, to flush out any intruders, Sgt Don lobbed several grenades around the platoon position.", options: { a: "Hid", b: "threw", c: "saved", d: "stole" }, correct: "b" },
  { id: 282, question: "A: The kids have been rowdy all day. B: Rowdy they may have been, but at least nothing was broken. They were just ...", options: { a: "cooperative", b: "intimidated", c: "surprised", d: "rambunctious" }, correct: "d" },
  { id: 283, question: "That story is not meant to be taken literally; it is ...", options: { a: "an allegory", b: "a narrative", c: "an epic", d: "a tradition" }, correct: "a" },
  { id: 284, question: "At the ceremony as the announcer mentioned something about a fallen comrade we suddenly heard the bugle call. what did they hear?", options: { a: "flaps", b: "maps", c: "taps", d: "laps" }, correct: "c" },
  { id: 285, question: "We finally realized that we needed to jettison the cargo.", options: { a: "Protect", b: "throw overboard", c: "load quickly", d: "take inventory of" }, correct: "b" },
  { id: 286, question: "The cost of the tomatoes, beans, onions, and apples ...a lot less than I expected.", options: { a: "have been", b: "was", c: "are", d: "were" }, correct: "b" },
  { id: 287, question: "What did he do yesterday? ...", options: { a: "He began his new class", b: "He is beginning his new class", c: "He begin his new class", d: "He begins his new class" }, correct: "a" },
  { id: 288, question: "Before I could write any of the vocabulary words in my notebook, someone ...the board completely.", options: { a: "Was erase", b: "is erasing", c: "erased", d: "is erased" }, correct: "c" },
  { id: 289, question: "I am pleased with the results of the ECL test.", options: { a: "happy", b: "uniformed", c: "angry", d: "unhappy" }, correct: "a" },
  { id: 290, question: "Suzan can\'t remember ...", options: { a: "what she gave it to me", b: "what did she give me", c: "if she gave it to me or not", d: "if or not she gave me" }, correct: "b" },
  { id: 291, question: "The instructors here are very ...that they never permit anyone to leave without written permission.", options: { a: "strict", b: "lazy", c: "guilty", d: "confident" }, correct: "a" },
  { id: 292, question: "Your fight will depart at 10:45 am.", options: { a: "Take off", b: "take over", c: "take apart", d: "take on" }, correct: "a" },
  { id: 293, question: "Before the fire truck arrived, the house ...down.", options: { a: "Had already burned", b: "already burns", c: "did already burned", d: "was already burn" }, correct: "a" },
  { id: 294, question: "The parachutist ...his legs when he landed roughly among some rocks.", options: { a: "hurt", b: "hurting", c: "hurts", d: "hurted" }, correct: "a" },
  { id: 295, question: "John F. Kennedy ...in 1963.", options: { a: "Is assassinate", b: "was assassinated", c: "was assassinate", d: "assassinate" }, correct: "b" },
  { id: 296, question: "Divide the ammo evenly ...all four units.", options: { a: "into", b: "between", c: "through", d: "among" }, correct: "d" },
  { id: 297, question: "Ron: Do you know anything about the operation Tommy is going to have? Susan: No, I\'m not familiar with that ...procedure.", options: { a: "surgical", b: "surge", c: "surgery", d: "surgeon" }, correct: "a" },
  { id: 298, question: "I dread ...to the dentist.", options: { a: "Gone", b: "going", c: "goes", d: "go" }, correct: "b" },
  { id: 299, question: "John: \"I\'ll drive you home, I think I\'m the only one here that\'s sober.\" John says that he is ...", options: { a: "not drunk", b: "efficient", c: "tolerant", d: "calm" }, correct: "a" },
  { id: 300, question: "Tom took a pratfall and tumbled down the stairs.", options: { a: "Tom fell down the stairs.", b: "First, Tom had something to eat, and then he worked on the stairs.", c: "Tom got a tool and repaired the stairs.", d: "Tom got a beverage and sat on the stairs." }, correct: "a" },
  { id: 301, question: "The captain made some very astute comments about the proposed changes.", options: { a: "shrewd", b: "verbose", c: "boorish", d: "asinine" }, correct: "a" },
  { id: 302, question: "She was up a creek without a paddle.", options: { a: "angry", b: "in time", c: "in prosperity", d: "in difficulty" }, correct: "d" },
  { id: 303, question: "I like your necklace; yours and mine are the same.", options: { a: "commercial", b: "equivalent", c: "identical", d: "resemble" }, correct: "c" },
  { id: 304, question: "Many people are rushing towards the gates.", options: { a: "running across", b: "moving slowly", c: "shouting", d: "moving fast" }, correct: "d" },
  { id: 305, question: "The hurricane destroyed many houses in the town yesterday.", options: { a: "big storm", b: "thunder", c: "snow", d: "light rain" }, correct: "a" },
  { id: 306, question: "The student was very rude.", options: { a: "Nice", b: "impolite", c: "polite", d: "nervous" }, correct: "b" },
  { id: 307, question: "She failed her English test.", options: { a: "Passed", b: "made", c: "liked", d: "didn\'t pass" }, correct: "d" },
  { id: 308, question: "What we want ...some of those cakes.", options: { a: "Are", b: "be", c: "is", d: "am" }, correct: "a" },
  { id: 309, question: "I don\'t feel like ...it.", options: { a: "To doing", b: "doing", c: "do", d: "to do" }, correct: "b" },
  { id: 310, question: "...all very well trained and professional.", options: { a: "A staff is", b: "All staffs is", c: "Our staff are", d: "Our staffs is" }, correct: "c" },
  { id: 311, question: "Mark is ...nice little boy!", options: { a: "Such a", b: "so", c: "such an", d: "too" }, correct: "a" },
  { id: 312, question: "Mark said he wanted to go to ...for dinner on his birthday.", options: { a: "those French restaurant", b: "Italy restaurant", c: "a Indonesian restaurant", d: "a Japanese restaurant" }, correct: "d" },
  { id: 313, question: "The police said that last night\'s fire in the hotel ...in the kitchen.", options: { a: "has started", b: "had started", c: "have started", d: "was going to start" }, correct: "b" },
  { id: 314, question: "My dentist ...clean my teeth more carefully.", options: { a: "Told to", b: "told me to", c: "said me to", d: "said that" }, correct: "b" },
  { id: 315, question: "A: What does your brother do? B: He works for a ...office furniture.", options: { a: "company that makes", b: "company where makes", c: "company, which makes", d: "company makes" }, correct: "a" },
  { id: 316, question: "In the winter, it is cold ...wet.", options: { a: "and", b: "so", c: "but", d: "while" }, correct: "a" },
  { id: 317, question: "I really miss ...in London.", options: { a: "To live", b: "lives", c: "living", d: "live" }, correct: "c" },
  { id: 318, question: "Have you ...finished?", options: { a: "Only", b: "yet", c: "already", d: "still" }, correct: "c" },
  { id: 319, question: "The hotel ...we stayed was good.", options: { a: "What", b: "which", c: "where", d: "who" }, correct: "c" },
  { id: 320, question: "Stratford is the town ...Shakespeare was born in.", options: { a: "Where", b: "which", c: "what", d: "who" }, correct: "b" },
  { id: 321, question: "These shoes ...leather.", options: { a: "Is made by", b: "are made from", c: "is made from", d: "made from" }, correct: "b" },
  { id: 322, question: "...a little dog in the park.", options: { a: "There is", b: "There are", c: "There", d: "Is there" }, correct: "a" },
  { id: 323, question: "Would you like my old TV ...your camera?", options: { a: "In exchange for", b: "in regard to", c: "in connection with", d: "in place" }, correct: "a" },
  { id: 324, question: "...his awkwardness, he was fired.", options: { a: "Consequently", b: "In spite of", c: "As a result of", d: "Because" }, correct: "c" },
  { id: 325, question: "They\'d better ... a taxi.", options: { a: "taking", b: "took", c: "take", d: "to take" }, correct: "c" },
  { id: 326, question: "I ...him clean his room.", options: { a: "Got", b: "made", c: "asked", d: "get" }, correct: "b" },
  { id: 327, question: "Ashley ...now.", options: { a: "Had a broken arm", b: "had a broke arm", c: "had a breaking arm", d: "had a break" }, correct: "a" },
  { id: 328, question: "He is the man ...lives just beside us.", options: { a: "What", b: "who", c: "where", d: "whom" }, correct: "b" },
  { id: 329, question: "He ...me that he finished the project.", options: { a: "told", b: "said", c: "tell", d: "says" }, correct: "a" },
  { id: 330, question: "He ...the black jacket.", options: { a: "choosed", b: "choosing", c: "chose", d: "chosen" }, correct: "c" },
  { id: 331, question: "Collins ...", options: { a: "stops smoking", b: "didn\'t smoke", c: "smokes now", d: "never" }, correct: "d" },
  { id: 332, question: "...a few minutes.", options: { a: "at", b: "by", c: "in", d: "on" }, correct: "c" },
  { id: 333, question: "Rita ...buy a car next month.", options: { a: "have", b: "will", c: "has to", d: "won\'t" }, correct: "b" },
  { id: 334, question: "Jim didn\'t go to the game and ...", options: { a: "I didn\'t either", b: "didn\'t I either", c: "so I didn\'t", d: "so did I" }, correct: "a" },
  { id: 335, question: "Molly, \"Yes, I ...it 2 hours ago.\"", options: { a: "eaten", b: "ate", c: "eated", d: "eat" }, correct: "b" },
  { id: 336, question: "The students succeeded ...the test was easy.", options: { a: "So", b: "to", c: "but", d: "because" }, correct: "d" },
  { id: 337, question: "People think that the earthquake was a ...", options: { a: "Cavity", b: "cavalier", c: "calamity", d: "cavil" }, correct: "c" },
  { id: 338, question: "He ... the laws.", options: { a: "supports", b: "violates", c: "protests", d: "compels" }, correct: "b" },
  { id: 339, question: "He ...his mistakes.", options: { a: "Mediated", b: "acknowledged", c: "promoted", d: "advocated" }, correct: "b" },
  { id: 340, question: "He wants my ...", options: { a: "Recommendation", b: "force", c: "well-being", d: "destruction" }, correct: "a" },
  { id: 341, question: "Rabbits ...to eat carrots.", options: { a: "Like", b: "are like", c: "liking", d: "likes" }, correct: "a" },
  { id: 342, question: "Yesterday was ...than today.", options: { a: "Colder", b: "more cold", c: "coldest", d: "the most cold" }, correct: "a" },
  { id: 343, question: "...car is white.", options: { a: "My", b: "I", c: "Me", d: "Mine" }, correct: "a" },
  { id: 344, question: "A horse can run ...a cow.", options: { a: "Faster than", b: "more fastly than", c: "as fast than", d: "more faster than" }, correct: "a" },
  { id: 345, question: "Yesterday, I ...eat well.", options: { a: "Didn\'t", b: "don\'t", c: "does", d: "doesn\'t" }, correct: "a" },
  { id: 346, question: "A: You ought to study hard, our test is tomorrow. B: Yes, we ...", options: { a: "Must", b: "will", c: "have", d: "should" }, correct: "d" },
  { id: 347, question: "The workers ...by the hour.", options: { a: "paying", b: "are paid", c: "will be pay", d: "pay" }, correct: "b" },
  { id: 348, question: "I haven\'t visited the Egyptian museum ...", options: { a: "Never", b: "none", c: "yet", d: "still" }, correct: "c" },
  { id: 349, question: "They said ...had to pay for it.", options: { a: "Their", b: "us", c: "we", d: "our" }, correct: "c" },
  { id: 350, question: "Oranges ...in cold countries.", options: { a: "Had not been grown", b: "are not grown", c: "growing", d: "haven\'t been" }, correct: "b" },
  { id: 351, question: "I found ...coffee in the pot. It was not enough to fill the cup.", options: { a: "A few", b: "many", c: "little", d: "few" }, correct: "c" },
  { id: 352, question: "He acts as if he ...a beautiful woman before.", options: { a: "Did never see", b: "never seen", c: "had never seen", d: "was never seen" }, correct: "c" },
  { id: 353, question: "The rich man hid the money, but it ...", options: { a: "was stolen", b: "would have been stolen", c: "can be stolen", d: "had been stealing" }, correct: "a" },
  { id: 354, question: "By the time I graduate in six weeks, I ...at least 20 tests here at DLI.", options: { a: "Had taken", b: "would have taken", c: "took", d: "will have taken" }, correct: "d" },
  { id: 355, question: "The news about the tornados in Oklahoma and Kansas ...very bad.", options: { a: "Have been", b: "is", c: "are", d: "were" }, correct: "b" },
  { id: 356, question: "Tom gave Mary a couple of cute teddy bears. Then, he gave her ...flowers.", options: { a: "Dozen", b: "a dozen of", c: "a dozen", d: "dozen of" }, correct: "c" },
  { id: 357, question: "This armchair is not very heavy.", options: { a: "It is expensive", b: "it is light", c: "it is valuable", d: "it is cheap" }, correct: "b" },
  { id: 358, question: "There is a possibility of rain tomorrow.", options: { a: "It must rain", b: "it did rain", c: "it might rain", d: "it will rain" }, correct: "c" },
  { id: 359, question: "This car was manufactured in 2005.", options: { a: "delivered", b: "bought", c: "sent", d: "made" }, correct: "d" },
  { id: 360, question: "Water ...at 100 degrees Celsius.", options: { a: "Freezes", b: "freeze", c: "boil", d: "boils" }, correct: "d" },
  { id: 361, question: "This jacket is very costly.", options: { a: "Cheap", b: "nice", c: "expensive", d: "priceless" }, correct: "c" },
  { id: 362, question: "Please, sir. How much is that ...of shoes?", options: { a: "Pair", b: "couple", c: "pear", d: "bar" }, correct: "a" },
  { id: 363, question: "Your palm is part of your ...", options: { a: "arm", b: "hand", c: "foot", d: "head" }, correct: "b" },
  { id: 364, question: "CENTCOM is one of nine...commands in the Department of Defense.", options: { a: "Activated", b: "defined", c: "unified", d: "provided" }, correct: "c" },
  { id: 365, question: "A violent sudden attack is referred to as a(n) ...", options: { a: "Firing", b: "assault", c: "pressure", d: "impression" }, correct: "b" },
  { id: 366, question: "It is hard for me to swallow because I have a sore ...", options: { a: "Wrist", b: "throat", c: "ankle", d: "knee" }, correct: "b" },
  { id: 367, question: "I\'m not sure about where he got this negative influence – may be from one of his siblings.", options: { a: "Brothers or sisters", b: "friends", c: "colleagues", d: "principles" }, correct: "a" },
  { id: 368, question: "To our surprise, it was incredibly hot last summer.", options: { a: "Moderately", b: "extremely", c: "not very", d: "slightly" }, correct: "b" },
  { id: 369, question: "A: How do you ...these low test scores? B: I know the explanation.", options: { a: "Get across", b: "make up", c: "think through", d: "account for" }, correct: "d" },
  { id: 370, question: "Lines that are at a 90-degree angle to each other are ...", options: { a: "not touching", b: "curved", c: "parallel", d: "perpendicular" }, correct: "d" },
  { id: 371, question: "In the past, people worked and tilled with simple, crude, basic. Tools were ...", options: { a: "Advanced", b: "sophisticated", c: "primitive", d: "polished" }, correct: "c" },
  { id: 372, question: "This tax should be abolished.", options: { a: "Encouraged", b: "supported", c: "reduced", d: "ended" }, correct: "d" },
  { id: 373, question: "He can\'t administer the school.", options: { a: "Reconstruct", b: "facilitate", c: "manage", d: "join" }, correct: "c" },
  { id: 374, question: "The live in squalid conditions here.", options: { a: "Prosperity", b: "misery", c: "wealth", d: "advance" }, correct: "b" },
  { id: 375, question: "When the police arrived, the men tried to flee.", options: { a: "Affiliate", b: "engage", c: "convene", d: "escape" }, correct: "d" },
  { id: 376, question: "The troops in the field need to take hot showers as soon as possible. We are concerned about their...", options: { a: "Hydraulics", b: "hyena", c: "hygiene", d: "hyphen" }, correct: "c" },
  { id: 377, question: "In those ancient times his ideas about religion were considered ...", options: { a: "Hearsay", b: "heresy", c: "heritage", d: "hereafter" }, correct: "b" },
  { id: 378, question: "Fred\'s beliefs about a supreme being reveal that he is less of an ...than he thinks he is .", options: { a: "a chaperon", b: "a steward", c: "a ruffian", d: "an atheist" }, correct: "d" },
  { id: 379, question: "we are having inclement weather.", options: { a: "Sunny", b: "stormy", c: "dry", d: "mild" }, correct: "b" },
];